# Generated by Django 4.1 on 2022-09-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-12-29'),
            preserve_default=False,
        ),
    ]
